#!/bin/bash

# USAGE: kitt recreate [flags] --  args
#
# Calls docker-compose to remove containers and bring them up from scratch.
# Use recreate when configuration changes since restart will retain the running
# config.
#
# args: arguments to docker-compose

function main {
  docker-compose rm -f -s "$@"
  kitt up "$@"
}

source sub "$0" "$@"
