#!/bin/bash

#- Copyright 2020 Authors of kitt
#-
#- Licensed under the Apache License, Version 2.0 (the "License");
#- you may not use this file except in compliance with the License.
#- You may obtain a copy of the License at
#-
#-     http://www.apache.org/licenses/LICENSE-2.0
#-
#- Unless required by applicable law or agreed to in writing, software
#- distributed under the License is distributed on an "AS IS" BASIS,
#- WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#- See the License for the specific language governing permissions and
#- limitations under the License.

# USAGE: kitt up [flags] -- args
#
# Calls docker-compose up to bring up services.
#
# args: arguments to docker-compose

function options {
  DEFINE_boolean fg "$FLAGS_FALSE" "run in the foreground" D
}

function main {
  docker-compose up $(if [[ "$FLAGS_fg" == "$FLAGS_FALSE" ]]; then echo "-d"; fi) "$@"
}

source sub "$0" "$@"
