#!/bin/bash

#- Copyright 2020 Authors of kitt
#-
#- Licensed under the Apache License, Version 2.0 (the "License");
#- you may not use this file except in compliance with the License.
#- You may obtain a copy of the License at
#-
#-     http://www.apache.org/licenses/LICENSE-2.0
#-
#- Unless required by applicable law or agreed to in writing, software
#- distributed under the License is distributed on an "AS IS" BASIS,
#- WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#- See the License for the specific language governing permissions and
#- limitations under the License.

# USAGE: kitt down [flags] args
#
# Calls docker-compose down to shut down services.  Services that are not
# defined in docker-compose.yml will be removed.
#
# args: arguments to docker-compose

function options {
  true
}

function main {
  docker-compose down --remove-orphans "$@"
}

source sub "$0" "$@"
