#!/bin/bash

# USAGE: kitt recycle [flags] --  args
#
# Calls docker-compose build/pull to get the latest images and recreates
# services.
#
# args: arguments to docker-compose

function options {
  true
}

function main {
  docker-compose build --pull "$@"
  kitt recreate "$@"
}

source sub "$0" "$@"
