#!/bin/bash

# USAGE: kitt logs [flags] --  args
#
# Calls docker-compose logs to tail service logs
#
# args: arguments to docker-compose

function options {
  true
}

function main {
  docker-compose logs -f "$@"
}

source sub "$0" "$@"
