#!/bin/bash

#- Copyright 2020 Authors of kitt
#-
#- Licensed under the Apache License, Version 2.0 (the "License");
#- you may not use this file except in compliance with the License.
#- You may obtain a copy of the License at
#-
#-     http://www.apache.org/licenses/LICENSE-2.0
#-
#- Unless required by applicable law or agreed to in writing, software
#- distributed under the License is distributed on an "AS IS" BASIS,
#- WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#- See the License for the specific language governing permissions and
#- limitations under the License.

# USAGE: kitt consul args
#
# Calls consul with server set to the host consul server.
#
# args: arguments to consul

function options {
  true
}

function main {
  if [[ -f .env ]]; then
    source .env
    export CONSUL_HTTP_TOKEN
  fi
  env CONSUL_HTTP_ADDR=http://consul.kitt.run:8500 consul "$@"
}

source sub "$0" "$@"
