#!/bin/bash

# USAGE: kitt restart [flags] --  args
#
# Calls docker-compose restart to restart services.  Does not reload
# configuration; use recreate for that.
#
# args: arguments to docker-compose

function options {
  true
}

function main {
  docker-compose restart "$@"
}

source sub "$0" "$@"
