#!/bin/bash

# USAGE: kitt down [flags] args
#
# Calls docker-compose down to shut down services.  Services that are not
# defined in docker-compose.yml will be removed.
#
# args: arguments to docker-compose

function main {
  docker-compose down --remove-orphans "$@"
}

source sub "$0" "$@"
