#!/usr/bin/env bash

function main {
  set -x

  local ip_unbound="$(host unbound | awk '{print $NF}')"
  local ip_consul="$(host consul | awk '{print $NF}')"

  (
    sleep 30
    perl -pe "s{^server=.*}{server=${ip_unbound}}" -i /etc/dnsmasq.d/01-pihole.conf
    echo "server=/consul/${ip_consul}#8600" >> /etc/dnsmasq.d/01-pihole.conf
    pihole restartdns
  ) &

  if [[ "$#" == 0 ]]; then
    sudo pihole -a -p ""
    set -- /s6-init
  fi

  exec "$@"
}

main "$@"
